# Generated by Django 4.2.1 on 2023-08-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_prducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prducts',
            new_name='products',
        ),
    ]
