# Generated by Django 4.2.1 on 2023-09-08 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_mymodel_alter_products_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='products',
            name='my_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
